# Generated by Django 5.1.1 on 2024-09-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('grade', models.IntegerField()),
                ('iep', models.BooleanField()),
                ('plan504', models.BooleanField()),
                ('eld', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.BooleanField(verbose_name=False)),
                ('admininistrator', models.BooleanField(verbose_name=False)),
                ('dean', models.BooleanField(verbose_name=False)),
                ('counselor', models.BooleanField(verbose_name=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=24)),
                ('subject', models.CharField(max_length=24)),
                ('credits', models.FloatField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staffer')),
                ('students', models.ManyToManyField(to='main_app.student')),
            ],
        ),
    ]
