# Generated by Django 5.1.1 on 2024-09-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_staffer_admininistrator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffer',
            old_name='admininistrator',
            new_name='administrator',
        ),
    ]
