# Generated by Django 5.1.1 on 2024-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_staffer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('E', 'English Language Arts'), ('H', 'History'), ('M', 'Math'), ('S', 'Science')], default='E', max_length=1),
        ),
    ]
