# Generated by Django 5.1.1 on 2024-09-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_course_title_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='eld',
            field=models.CharField(choices=[('N', 'Not applicable'), ('1', '1 - Entering'), ('2', '2 - Emerging'), ('3', '3 - Developing'), ('4', '4 - Expanding'), ('5', '5 - Bridging'), ('6', 'FLEP')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='iep',
            field=models.BooleanField(verbose_name='IEP'),
        ),
        migrations.AlterField(
            model_name='student',
            name='plan504',
            field=models.BooleanField(verbose_name='504 Plan'),
        ),
    ]
