# Generated by Django 5.1.1 on 2024-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_student_eld_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='eld',
            field=models.CharField(choices=[('N', 'Not applicable'), ('1', '1 - Entering'), ('2', '2 - Emerging'), ('3', '3 - Developing'), ('4', '4 - Expanding'), ('5', '5 - Bridging'), ('6', 'FLEP')], default='N', max_length=1, verbose_name='ELD'),
        ),
    ]
