# Generated by Django 5.1.1 on 2024-09-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_student_eld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='eld',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('1', '1 - Entering'), ('2', '2 - Emerging'), ('3', '3 - Developing'), ('4', '4 - Expanding'), ('5', '5 - Bridging'), ('6', 'FLEP')], default='N/A', max_length=3, verbose_name='ELD'),
        ),
    ]
